#define DEBUG 1

#define WIRE_SLAVE_TOP_ADDRESS 8
#define WIRE_SLAVE_TOP_REQUEST_SIZE 6
#define WIRE_SLAVE_MOVE_REQUEST_SIZE 3

#define STOP 0
#define CLOCKWISE 1
#define ANTCLOCKWISE 2

#define CURTAIN_OPEN 0
#define CURTAIN_CLOSE 1
#define CURTAIN_STOP 2

#define CURTAIN_TIME 30
